version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
      - 8001:443
    depends_on:
      - db
    environment:
      SQL_CONNECTION_STRING: "server=db,1433;database=BlogSiteDb;uid=sa;pwd=MyLocalPassword123;TrustServerCertificate=True"
      FIREBASE_SECRET: ${FIREBASE_SECRET}
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    user: root
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "MyLocalPassword123"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - ./SQL/:/var/opt/mssql/data