version: "3.9"
services:
  api:
    build:
      context: ./WebAPI/
      dockerfile: Dockerfile
    ports:
      - 8000:80
      - 8001:443
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    user: root
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "MyStrongPassword123"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - blog_db_volume:/var/opt/mssql/data
volumes:
  blog_db_volume: